### ISSUE TITLE
Please create a ReadMe instructional page for tool.exe

### ISSUE THREAD

**Issue by TerriblyVexed** [microsoft/FHIR-Analytics-Pipelines#100]
Microsoft.Health.Fhir.Transformation.Cdm.Tool.exe is an invaluable tool for troubleshooting FhirToCdm. Please include instruction on it.

**Comment by QuanWanxx** [comment]
Have updated instruction for tool.exe in [fhir-to-cdm](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToCdm/docs/fhir-to-cdm.md) spec section 4.
