### ISSUE TITLE
Impossible to have a FHIR hostname that's different from the FHIR URL

### ISSUE THREAD

**Issue by oumasab** [microsoft/FHIR-Analytics-Pipelines#108]
I am trying to configure the Synapse Sync agent for a FHIR server that is exposed through a hostname that's different from its URL. I did give the function app a FHIR Data Reader role. 

- When I use the hostname for the parameter `Fhir Server Url`, I get an error where the access token is unable to be generated: 

Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: <**REMOVED: fhir hostname**>, Authority: . Exception Message: Tried the following 3 methods to get an access token, but none of them worked.\r\nParameters: Connection String: [No connection string specified], Resource: <**REMOVED: fhir hostname**>, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Failed after 5 retries. MSI ResponseCode: InternalServerError, Response: {\"StatusCode\":500,\"Message\":\"An unexpected error occured while fetching the AAD Token. Please contact support with this provided Correlation Id\",\"CorrelationId\":\"4fecc64e-60a0-4bc8-9e20-5523e47825c1\"}\r\nParameters: Connection String: [No connection string specified], Resource: <**REMOVED: fhir hostname**> Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio token provider file not found at \"C:\\local\\LocalAppData\\.IdentityService\\AzureServiceAuth\\tokenprovider.json\"\r\nParameters: Connection String: [No connection string specified], Resource: <**REMOVED: fhir hostname**>, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n\r\n\r\n   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, Boolean forceRefresh, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(String resource, String tenantId, Boolean forceRefresh, CancellationToken cancellationToken)\r\n   at Microsoft.Health.Fhir.Synapse.DataClient.Api.AzureAccessTokenProvider.GetAccessTokenAsync(String resourceUrl, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.DataClient\\Api\\AzureAccessTokenProvider.cs:line 47\r\n   at Microsoft.Health.Fhir.Synapse.DataClient.Api.FhirApiDataClient.SearchAsync(FhirSearchParameters searchParameters, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.DataClient\\Api\\FhirApiDataClient.cs:line 89\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Health.Fhir.Synapse.DataClient.Api.FhirApiDataClient.SearchAsync(FhirSearchParameters searchParameters, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.DataClient\\Api\\FhirApiDataClient.cs:line 89\r\n   at Microsoft.Health.Fhir.Synapse.Core.Tasks.TaskExecutor.ExecuteAsync(TaskContext taskContext, JobProgressUpdater progressUpdater, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Tasks\\TaskExecutor.cs:line 70\r\n   at Microsoft.Health.Fhir.Synapse.Core.Jobs.JobExecutor.<>c__DisplayClass5_1.<<ExecuteAsync>b__1>d.MoveNext() in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Jobs\\JobExecutor.cs:line 74\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Health.Fhir.Synapse.Core.Jobs.JobExecutor.ExecuteAsync(Job job, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Jobs\\JobExecutor.cs:line 61\r\n   at Microsoft.Health.Fhir.Synapse.Core.Jobs.JobManager.RunAsync(CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Jobs\\JobManager.cs:line 81","ResumedJobId":"efa184faf7fa4e34aeadd1581a760050"}

- When I use the FHIR URL for the parameter `Fhir Server Url`, I get a 403 Forbidden error:

Health.Fhir.Synapse.Core.Exceptions.ExecuteTaskFailedException: Task execution failed\r\n ---> System.AggregateException: One or more errors occurred. (Search FHIR server failed. Search url: 'https://z-ago-dhp-aid-ew1-fhir01.azurehealthcareapis.com/Appointment?_lastUpdated=ge1970-01-01T00%3a00%3a00%2b00%3a00&_lastUpdated=lt2022-05-05T10%3a23%3a06.6073304%2b00%3a00&_count=1000&_sort=_lastUpdated'. )\r\n ---> Microsoft.Health.Fhir.Synapse.DataClient.Exceptions.FhirSearchException: Search FHIR server failed. Search url: '<**REMOVED: FHIR URL**>/Appointment?_lastUpdated=ge1970-01-01T00%3a00%3a00%2b00%3a00&_lastUpdated=lt2022-05-05T10%3a23%3a06.6073304%2b00%3a00&_count=1000&_sort=_lastUpdated'. \r\n ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).\r\n   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at Microsoft.Health.Fhir.Synapse.DataClient.Api.FhirApiDataClient.SearchAsync(FhirSearchParameters searchParameters, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.DataClient\\Api\\FhirApiDataClient.cs:line 77\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Health.Fhir.Synapse.DataClient.Api.FhirApiDataClient.SearchAsync(FhirSearchParameters searchParameters, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.DataClient\\Api\\FhirApiDataClient.cs:line 85\r\n   at Microsoft.Health.Fhir.Synapse.Core.Tasks.TaskExecutor.ExecuteAsync(TaskContext taskContext, JobProgressUpdater progressUpdater, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Tasks\\TaskExecutor.cs:line 70\r\n   at Microsoft.Health.Fhir.Synapse.Core.Jobs.JobExecutor.<>c__DisplayClass5_1.<<ExecuteAsync>b__1>d.MoveNext() in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Jobs\\JobExecutor.cs:line 74\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Health.Fhir.Synapse.Core.Jobs.JobExecutor.ExecuteAsync(Job job, CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Jobs\\JobExecutor.cs:line 61\r\n   at Microsoft.Health.Fhir.Synapse.Core.Jobs.JobManager.RunAsync(CancellationToken cancellationToken) in D:\\a\\1\\s\\FhirToDataLake\\src\\Microsoft.Health.Fhir.Synapse.Core\\Jobs\\JobManager.cs:line 68","ResumedJobId":"d2ab4a23dde8494c91900f6babad8e81"}

Is there a way in the configuration we can distinguish between the URL used to generate the bearer token and the hostname used for the subsequent requests? 
Thank you !

**Comment by moria97** [comment]
hi oumasab, currently we only support Managed Identity authorization to access an Azure API for FHIR server url.
When using an Azure FHIR server url, have you granted the `FHIR Data Reader` role to the azure function instance? you can find more details [here](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/docs/Deployment.md#2-provide-access-of-the-fhir-server-to-the-azure-function)

**Comment by moria97** [comment]
There's no direct workaround for this as we are using same url to retrieve token and request data. I'm curious why you can't use the `https://xxxxxxx.azurehealthcareapis.com/`  url directly?

**Comment by oumasab** [comment]
It is due to the way that the FHIR API in my project is setup. It is only accessible via the hostname, requests directly to the `https://xxxxxxx.azurehealthcareapis.com/` are forbidden.

**Comment by oumasab** [comment]
The problem has been resolved by adding the Azure Function to the same VNET as our private FHIR server.
