### ISSUE TITLE
Coverage and DocumentReference Resources Parquet not generated 

### ISSUE THREAD

**Issue by shrikantnawale** [microsoft/FHIR-Analytics-Pipelines#121]
Observation: If a resource bundle contains "Coverage" Resource within  other resource e.g. "ExplanationOfBenefit" or "Claims" no parquet file is generated for the Coverage. This is an issue for us because Coverage details will most likely come as a referenced resource in other resources as per Fhir documentation http://build.fhir.org/coverage.html.
Similar issue is with DocumentReference Resource. DocumentReference resource mostly will be part of other resources http://hl7.org/fhir/R4/documentreference.html.

I tried uploading attached bundle and was expecting Parquet file for Coverage Resource but no file was generated.

[Ali918_Stokes453_f5aa3408-57b3-4c05-a1d3-e4511b4be50e.txt](https://github.com/microsoft/FHIR-Analytics-Pipelines/files/8983114/Ali918_Stokes453_f5aa3408-57b3-4c05-a1d3-e4511b4be50e.txt)

**Comment by moria97** [comment]
Hi @shrikantnawale,  by `within other resource` you mean the contained resources?

**Comment by shrikantnawale** [comment]
Yes, contained resources.

Thanks,
Shrikant

________________________________

**Comment by irenepjoseph** [comment]
Hi @shrikantnawale this feature request has been provided to engineering team for prioritization. Thanks

**Comment by RuiyiC** [comment]
Added to backlog and closed.
