### ISSUE TITLE
Use with Non-MS-FHIR-Server

### ISSUE THREAD

**Issue by ZuSe** [microsoft/FHIR-Analytics-Pipelines#123]
Is it possible to use the agent with a custom fhir server such as HAPI or IBM?

From my perspective it should be possible and all we have to do would be to customize the authentication part, am I right with this assumption?

Best
Patrick

**Comment by irenepjoseph** [comment]
Hi @ZuSe 
Yes, you can refer to [FHIRtoDataLake](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/docs/Deployment.md) documentation, ensure correct authentication and access to FHIR is setup, update the Powershell script for use with non-Azure FHIR servers. 
Let us know how it goes.

**Comment by moria97** [comment]
> Is it possible to use the agent with a custom fhir server such as HAPI or IBM?
> 
> From my perspective it should be possible and all we have to do would be to customize the authentication part, am I right with this assumption?
> 
> Best Patrick

Yes, looks like only the auth part to FHIR server should be customized according to your own setting. Please let us know if there are any issues
