### ISSUE TITLE
Deletions not reflected in Parquet files

### ISSUE THREAD

**Issue by ben113311** [microsoft/FHIR-Analytics-Pipelines#124]
After deleting resources from FHIR Server the Parquet files are not updated and resources continue to display in Synapse queries.

**Comment by QuanWanxx** [comment]
Hi, currently the pipeline continuously sync up **new/updated** data from FHIR server to data lake, **delete** is not supported now, And we are investigating some solutions for that.

**Comment by irenepjoseph** [comment]
Setting up FHIR events to track for deleted resources, listing them in the Data Lake and excluding deleted resource in Synapse is a workaround. Delta Lake format instead of Data Lake is an option
