### ISSUE TITLE
Issue while deploying the PowerShell Script in Step 6 of performing FHIR to Synapse Sync Agent

### ISSUE THREAD

**Issue by SD-14** [microsoft/FHIR-Analytics-Pipelines#172]
Hello,

Day 1:
While running through this repo, came across an issue in step 6 while executing the PS script:

![image](https://user-images.githubusercontent.com/83011430/191768595-66833f72-2434-4f58-b1e0-c7d549b14795.png)

Verified the content of the SQL Source File “Basic” and looks fine, double-checked the permissions as well and tried running it again the second time as an Administrator in PS, but came across the same issue again.

Day 2:
Reran the PS script in step  6 again today, and this time it was executed successfully:

![image](https://user-images.githubusercontent.com/83011430/191769095-6bb464f1-d7ab-4c94-9637-eb7c1dee3e00.png)

Reporting this observation to understand why did it fail the first time? If somebody could help, that'd be great!

**Comment by mikaelweave** [comment]
This appears to be due to folders not existing in the Data Lake. There is an error in this function.

https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/scripts/Set-SynapseEnvironment.ps1#L165

**Comment by irenepjoseph** [comment]
@tongwu-msft for your review

**Comment by moria97** [comment]
@SD-14  Thanks for reporting this issue. This bug has been fixed in [PR #177](https://github.com/microsoft/FHIR-Analytics-Pipelines/pull/177).
