### ISSUE TITLE
FhirToDataLake - Any plans to migrate to Azure Function 4.x

### ISSUE THREAD

**Issue by VOVELEE** [microsoft/FHIR-Analytics-Pipelines#186]
I have noticed that the function currently requires FUNCTIONS_EXTENSION_VERSION set to ~2 and WEBSITE_NODE_DEFAULT_VERSION set to ~10. [Link](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json)
Are there any plans these versions to be updated and tested?
 
The reason behind my questions is:
•	FUNCTIONS_EXTENSION_VERSION ~2 will be out of support after December 3, 2022 – Link: [Azure Functions runtime versions overview | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cwindows%2Cin-process%2Cv4&pivots=programming-language-csharp)
•	Node JS  10 is not available on any other Function extension version

**Comment by moria97** [comment]
@VOVELEE Thanks for this good suggestion. We have made the update in #189 .
By the way, we are working on using ACI as hosting instance instead of Azure Function, and the release for the container deployment will come out in about November. You can find this [template](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/deploy/templates/DeployContainer.json) for preview.

**Comment by VOVELEE** [comment]
Thanks @moria97 .
Does this mean that:
- Azure Function support will be discontinued in November and we will have to migrate to ACI in order to get the new functions
- you will support both ACI and Azure Functions after November release?

**Comment by moria97** [comment]
@VOVELEE ACI and Azure Function only differs in hosting model. We will still provide the Azure Function template and you can choose which suits you better.

**Comment by ben113311** [comment]
Hi @moria97, I see that the function extension version has been updated to ~4, but how can we apply this change to existing deployments? Do we need to re-deploy, or is it okay to just modify the application setting in the existing Azure Function?

**Comment by moria97** [comment]
> Azure

Hi, I would recommend you redeploy a new function to avoid possible conflicts. And for new deployments,  you can also try the [Container App deployment template](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2FFHIR-Analytics-Pipelines%2Fmain%2FFhirToDataLake%2Fdeploy%2Ftemplates%2FContainerApp%2FDeployFhirPipelineToContainerApp.json) which has better capability to scale out in our scenario.
