### ISSUE TITLE
Automatically add the FHIR Data Reader Role Assignment for the Function App

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/FHIR-Analytics-Pipelines#199]
If Managed Identity is enabled for the Azure FHIR to Parquet pipeline, it would be super great for the deployment template to automatically deploy a "FHIR Reader" role assignment for the function app on the FHIR Service / API for FHIR.

It's possible to parse the URL and determine which SKU is being used. Then you can attempt to deploy a role assignment.

**Comment by moria97** [comment]
Hi @mikaelweave , it's possible to add a role assignment to FHIR server automatically in arm template and we used to try grant FHIR data reader role in deployment by default. However, there have been some deployment failures reported as the existing FHIR server instance could be in some other resource group/subscription and the user lacks access to grant FHIR permission. So currently we requires an additional step to grant FHIR access manually.
Thanks for the good suggestion. We will revisit the auto-authorization behavior after the new release.

**Comment by mikaelweave** [comment]
Understood - I will start using my own template for our FHIR Service sample repos.

Thanks!
Mikael
