### ISSUE TITLE
PackageLink broken URL

### ISSUE THREAD

**Issue by CedricSteenbeke** [microsoft/FHIR-Analytics-Pipelines#49]
The ADF pipeline crashes on the GenerateSchema step since the default value for the PackageLink parameter is no longer available.
In the ReadMe it states to not change this parameter.
Could this link be updated to the right location where a valid BatchExecutor.zip exists?
current link is: 
https://github.com/microsoft/FHIR-Analytics-Pipelines/releases/download/untagged-d8e03f9d7aef82990abe/BatchExecutor.zip

stderr.txt content:
````Invoke-WebRequest : Not Found
At line:1 char:1
+ Invoke-WebRequest -Uri 'https://github.com/microsoft/FHIR-Analytics-P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
````

**Comment by CedricSteenbeke** [comment]
Seems like the releases are available again.
could the default link in the package be updated to the latest release?
https://github.com/microsoft/FHIR-Analytics-Pipelines/releases/download/v0.2.0/BatchExecutor.zip

**Comment by irenepjoseph** [comment]
@tongwu-msft is there any further action on the package update?

**Comment by mikaelweave** [comment]
@tongwu-msft Can you remove this old package?? We copied the ARM template and were accidentally using an old version for a while. 

https://fhiranalyticspipeline.blob.core.windows.net/builds/Microsoft.Health.Fhir.Synapse.FunctionApp.zip
