### ISSUE TITLE
Azure Function getting 401 error when calling Fhir

### ISSUE THREAD

**Issue by jmarti326** [microsoft/FHIR-Analytics-Pipelines#89]
When looking at the Application Insight, I have seen that the Azure Function has trouble authenticating with the Fhir API. Azure Function has Fhir Reader Role, as seen in the image below.

Please feel free to ask any other data that might be helpful.

![image](https://user-images.githubusercontent.com/4348632/155587688-cc81d747-86bc-4fe9-b2e2-c6765adc10d3.png)

![image](https://user-images.githubusercontent.com/4348632/155587839-28634657-da35-4178-ac62-e043c3397c2b.png)

![image](https://user-images.githubusercontent.com/4348632/155588032-f15846e0-8673-4985-b603-6c1091f03536.png)

Example of Log

Exception while executing function: Functions.JobManagerFunction Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Task execution failed)
 ---> Microsoft.Health.Fhir.Synapse.Scheduler.Exceptions.ExecuteTaskFailedException: Task execution failed
 ---> System.AggregateException: One or more errors occurred. (Search FHIR server failed. Search url: 'https://fhir-analytics.azurehealthcareapis.com/AdverseEvent?_lastUpdated=ge1970-01-01T00%3a00%3a00%2b00%3a00&_lastUpdated=lt2022-02-21T19%3a56%3a19.6280037%2b00%3a00&_count=1000&_sort=_lastUpdated'. )
 ---> Microsoft.Health.Fhir.Synapse.DataSource.Exceptions.FhirSearchException: Search FHIR server failed. Search url: 'https://fhir-analytics.azurehealthcareapis.com/AdverseEvent?_lastUpdated=ge1970-01-01T00%3a00%3a00%2b00%3a00&_lastUpdated=lt2022-02-21T19%3a56%3a19.6280037%2b00%3a00&_count=1000&_sort=_lastUpdated'. 
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Health.Fhir.Synapse.DataSource.FhirDataClient.SearchAsync(TaskContext context, CancellationToken cancellationToken) in D:\a\1\s\FhirToDataLake\src\Microsoft.Health.Fhir.Synapse.DataSource\FhirDataClient.cs:line 119
   --- End of inner exception stack trace ---
   at Microsoft.Health.Fhir.Synapse.DataSource.FhirDataClient.SearchAsync(TaskContext context, CancellationToken cancellationToken) in D:\a\1\s\FhirToDataLake\src\Microsoft.Health.Fhir.Synapse.DataSource\FhirDataClient.cs:line 119
   at Microsoft.Health.Fhir.Synapse.DataSource.FhirDataClient.GetAsync(TaskContext context, CancellationToken cancellationToken) in D:\a\1\s\FhirToDataLake\src\Microsoft.Health.Fhir.Synapse.DataSource\FhirDataClient.cs:line 61
   at Microsoft.Health.Fhir.Synapse.Scheduler.Tasks.TaskExecutor.ExecuteAsync(TaskContext taskContext, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\1\s\FhirToDataLake\src\Microsoft.Health.Fhir.Synapse.Scheduler\Tasks\TaskExecutor.cs:line 70
   at Microsoft.Health.Fhir.Synapse.Scheduler.Jobs.JobManager.<>c__DisplayClass11_1.<<ExecuteJob>b__1>d.MoveNext() in D:\a\1\s\FhirToDataLake\src\Microsoft.Health.Fhir.Synapse.Scheduler\Jobs\JobManager.cs:line 206
   --- End of inner exception stack trace ---

**Comment by jmarti326** [comment]
Should I change the authentication setting in the Azure Function to something else?

![image](https://user-images.githubusercontent.com/4348632/155631838-8856cefe-70ee-4c6a-bb36-b7ee735452ea.png)

**Comment by jmarti326** [comment]
After changing the value to based on what I saw in the enum of the code the errors of authentication started to stop.
![image](https://user-images.githubusercontent.com/4348632/155640979-24920c62-055e-4aa8-92bf-b36768193b39.png)

![image](https://user-images.githubusercontent.com/4348632/155641059-53607b5c-0e58-4f81-896e-cd735dd9e406.png)

**Comment by QuanWanxx** [comment]
Hi,

When [deploying](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/docs/Deployment.md#1-deploy-the-pipeline) the Synapse Sync agent, are you select ```true``` for ```Authentication``` rather than default ```false``` in deployment page? 

Using the Azure API for FHIR or the FHIR service in Azure Healthcare APIs:

1. the ```Authentication``` should be ```true```.
2. Assign the ```FHIR Data Reader``` role to the Azure Function noted.

**Comment by jmarti326** [comment]
Hi Quan,

Seems like the documentation wording confused us.  We were understanding that if we wanted to ignore any type of authentication we could just have false.

![image](https://user-images.githubusercontent.com/4348632/155646348-6bbb88cd-a39a-446d-9b61-e20070d4afa7.png)

Thank you for the reply. :) Truly appreciate the help, and guidance.

**Comment by QuanWanxx** [comment]
> Hi Quan,
> 
> Seems like the documentation wording confused us. We were understanding that if we wanted to ignore any type of authentication we could just have false. At the end, making the change to the setting above, solved the issue. 🙌🏽
> 
> ![image](https://user-images.githubusercontent.com/4348632/155646348-6bbb88cd-a39a-446d-9b61-e20070d4afa7.png)
> 
> Thank you for the reply. 😊 Truly appreciate the help, and guidance.

Setting the ```Authentication``` should refer to FHIR server properties, maybe will update the document if more people feel the meaning is not clear.

Welcome to open another issue if you have other questions :)
