### ISSUE TITLE
Can you make batchexecutor.exe folder aware

### ISSUE THREAD

**Issue by TerriblyVexed** [microsoft/FHIR-Analytics-Pipelines#98]
Currently the --cdmFileSystem parameter is not folder aware. I cannot pass cdm/folder. Can you please make it so I can?
In my implementation I create folders with the date and runtime guid to track. 
cdm/20220307T164544-d8b2bbbd-5407-4a59-9cac-c7c95bad0061
But I have to pass 'cdm' in the pipeline and let \RunAdfCustomActivity.ps1 put the cdm.json files in the root, then have Copy operations to copy/move them into the folder.

**Comment by QuanWanxx** [comment]
Hi Terribly,

Do you mean when you use ```BatchExecutor.exe``` to transform data, it will throw exception if ```cdmFileSystem``` container doesn't exist? 

You can use use ```BatchExecutor.exe``` to ```generate-schema``` firstly, this will initialize and create the cdm folder, then to ```transform-data``` with exported FHIR ndjdon files. You can refer content in \RunAdfCustomActivity.ps1 for those 2 operations.

**Comment by TerriblyVexed** [comment]
No, I mean that if the Azure Blob Storage location that I want the results of generate-schema to go to is cdm\20220307T164544-d8b2bbbd-5407-4a59-9cac-c7c95bad0061 it will not work currently. It is only container aware, not folder aware. Thus you can only output the results to the blob container, not a blob path.

**Comment by QuanWanxx** [comment]
Currently we don't have plan to support specifying folder as the target to generate CDM metadata and CDM data.

Thanks for you suggestion, will consider this in future updates.
